export const light = {
  primary: "#16a085",
  secondary: "#e67e22",
  bgPrimary: "#fff",
  bgPrimaryAlpha: "#ffffff75",
  bgSecondary: "#ddd",
  bgSecondaryAlpha: "#dddddd75",
  bgTertiary: "#eeeeee",
  borderPrimary: "#313131",
  borderSecondary: "#fff",
  txtPrimary: "#313131",
  txtSecondary: "#fff",
  error: "#c0392b",
  warning: "#f1c40f",
  success: "#2ecc71",
  white: "#fff",
  black: "#313131",
  blackAlpha: "#31313175",
};

export const dark = {
  primary: light.primary,
  secondary: light.secondary,
  bgPrimary: "#515151",
  bgPrimaryAlpha: "#51515175",
  bgSecondary: "#313131",
  bgSecondaryAlpha: "#31313175",
  bgTertiary: "#414141",
  borderPrimary: light.borderSecondary,
  borderSecondary: light.borderPrimary,
  txtPrimary: light.txtSecondary,
  txtSecondary: light.txtPrimary,
  error: light.error,
  warning: light.warning,
  success: light.success,
  white: light.white,
  black: light.black,
  blackAlpha: light.blackAlpha,
};
